{
 "title": "Docker Prometheus Monitoring-emil Copy",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spr_request_depth" }
   ]
  },
  {
   "title": "Request Depth Max",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spr_request_depth_max" }
   ]
  },
  {
   "title": "Enqueued",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spr_scheduler_enqueued" }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "spr_downloader_response_bytes" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Items Dropped",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spr_item_dropped_count" }
   ]
  },
  {
   "title": "Items Scraped",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spr_item_scraped_count" }
   ]
  },
  {
   "title": "Scraped data MiB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scraped_file_size" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Items dropped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "spr_item_dropped_count", "legendFormat": "items dropped" }
   ]
  },
  {
   "title": "New items found",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "spr_item_scraped_count", "legendFormat": "items downloaded" }
   ]
  },
  {
   "title": "Probably visited",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "spr_visited_filter_duplicate" }
   ]
  },
  {
   "title": "INFO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "spr_log{level='INFO'}" }
   ]
  },
  {
   "title": "DEBUG",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "spr_log{level='DEBUG'}" }
   ]
  },
  {
   "title": "ERROR",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "spr_log{level='ERROR'}" }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "spr_log{level=\"CRITICAL\"}"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "spr_log{level=\"WARNING\"}"
    }
   ]
  },
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "RPi cpu temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_cpu_temperature", "legendFormat": "{{Raspberry Pi 4}}" }
   ]
  },
  {
   "title": "Raspberry Pi Load 1,5,15",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  },
  {
   "title": "Spider memory use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spr_memusage_max" }
   ]
  },
  { "title": "Container Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 12, "y": 51 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Running Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    }
   ]
  }
 ]
}